### PR TITLE
Ospf parser

### PR DESCRIPTION
**Pull request by sward1557**
Submitting a new Juniper parser for command "show ospf neighbor detail". Below you will see the results of us running the command through the parser file.
```
TASK [juniper_junos : print facts text] ***************************************************************************************************************
ok: [router1] => {
    "msg": {
        "capabilities": {
            "network_os": "junos",
            "network_os_hostname": "router1",
            "network_os_model": "srx340",
            "network_os_version": "15.1X49-D45"
        },
        "routing": {
            "10.0.10.1": {
                "area": "0.0.0.1",
                "interface": "st0.7",
                "ip": "10.0.10.1",
                "state": "Full",
                "uptime": "5d 07:39:53"
            },
            "10.0.3.1": {
                "area": "0.0.0.1",
                "interface": "st0.2",
                "ip": "10.0.3.1",
                "state": "Full",
                "uptime": "5d 20:58:09"
            },
            "10.0.4.1": {
                "area": "0.0.0.1",
                "interface": "st0.3",
                "ip": "10.0.4.1",
                "state": "Full",
                "uptime": "5d 20:58:13"
            },
            "10.0.5.1": {
                "area": "0.0.0.1",
                "interface": "st0.4",
                "ip": "10.0.5.1",
                "state": "Full",
                "uptime": "5d 10:59:13"
            },
            "10.0.6.1": {
                "area": "0.0.0.1",
                "interface": "st0.8",
                "ip": "10.0.6.1",
                "state": "Full",
                "uptime": "5d 18:49:44"
            },
            "10.0.7.1": {
                "area": "0.0.0.1",
                "interface": "st0.9",
                "ip": "10.0.7.1",
                "state": "Full",
                "uptime": "5d 20:59:31"
            },
            "10.0.8.1": {
                "area": "0.0.0.1",
                "interface": "st0.5",
                "ip": "10.0.8.1",
                "state": "Full",
                "uptime": "5d 20:40:12"
            },
            "10.0.9.1": {
                "area": "0.0.0.1",
                "interface": "st0.6",
                "ip": "10.0.9.1",
                "state": "Full",
                "uptime": "5d 12:42:33"
            },
            "10.1.1.1": {
                "area": "0.0.0.1",
                "interface": "st0.1",
                "ip": "10.1.1.1",
                "state": "Full",
                "uptime": "5d 20:58:32"
            }
        }
    }
}
```

### CODE REVIEW

**Comment by sward1557** [comment]
@ganessh is there something I need to take care of to complete this merge? 

Thanks

**Review by ganeshrn — APPROVED** [review]
@sward1557 Thank you for PR.
Can you please sign the PR so that CI is passed and PR get's merged
```
$ git commit --amend -s
$ git push origin <branch-name> --force
```

**Comment by ganeshrn** [comment]
@sward1557 DCO test is failing. Please pass `-s` while issuing `git commit` to sign this PR

**Comment by sward1557** [comment]
Closing in favor of #35

**Pull request closed without merging**
